# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "auto gift cart"
client_id = "92cd2bceb8d657cf34ff1c57eda4375c"
application_url = "https://amended-fears-descriptions-contributors.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://amended-fears-descriptions-contributors.trycloudflare.com/auth/callback",
  "https://amended-fears-descriptions-contributors.trycloudflare.com/auth/shopify/callback",
  "https://amended-fears-descriptions-contributors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myonestr.myshopify.com"
